### ISSUE TITLE
Invalid int literal

### ISSUE THREAD

**Issue by Silur** [radare/bokken#4]
Opening ANY exe file with bokken whether use analyze or not produces the same error:
```
Traceback (most recent call last):
  File "/usr/share/bokken/bokken.py", line 76, in <module>
    bokken()
  File "/usr/share/bokken/bokken.py", line 71, in bokken
    'radare' if args.radare else '',
  File "/usr/share/bokken/ui/main.py", line 395, in main
    BokkenGTKClient(target, backend)
  File "/usr/share/bokken/ui/main.py", line 163, in __init__
    self.tviews = textviews.TextViews(self.uicore, self)
  File "/usr/share/bokken/ui/textviews.py", line 148, in __init__
    self.right_notebook = rightnotebook.RightNotebook(self)
  File "/usr/share/bokken/ui/rightnotebook.py", line 46, in __init__
    self.create_tabs()
  File "/usr/share/bokken/ui/rightnotebook.py", line 98, in create_tabs
    self.add_info_elements_tab()
  File "/usr/share/bokken/ui/rightnotebook.py", line 152, in add_info_elements_tab
    self.uicore.get_full_file_info()
  File "/usr/share/bokken/ui/radare_core.py", line 469, in get_full_file_info
    self.full_fileinfo['eps'].append(['Entry0', hex(int(line))])
ValueError: invalid literal for int() with base 10: '{"vaddr":626184,"paddr":620040,"baddr":0,"laddr":0,"type":"program"}'
```

**Comment by hteso** [comment]
Hi,

That's an error that happens when using Bokken with another radare2 version; usually people using Bokken with radare2 from Git. It is fixed in Bokken development and will be released shortly.

In the mean time, Bokken 1.8 works **ONLY** with radare2 0.9.9:

[Compatibility](http://ingumadev.blogspot.de/2015/06/bokken-18.html)

**Comment by Silur** [comment]
Indeed, thank you :smile:
